version: "3.8"

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST=${TEST}
    container_name: rabbitmq
    ports:
      - "5671:5671" # RabbitMQ SSL port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./ssl:/etc/rabbitmq/ssl

