version: "3.8"

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CA_CERTIFICATE=${CA_CERTIFICATE}
        - SERVER_CERTIFICATE=${SERVER_CERTIFICATE}
        - SERVER_PRIVATE_KEY=${SERVER_PRIVATE_KEY}
        
    container_name: rabbitmq
    ports:
      - "5671:5671" # RabbitMQ SSL port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./ssl:/etc/rabbitmq/ssl

