version: '3.8'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5671:5671"  # RabbitMQ SSL port
      - "15672:15672"  # RabbitMQ management UI port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./ssl:/etc/rabbitmq/ssl
    environment:
      - CA_CERTIFICATE=${CA_CERTIFICATE}
    command: ["echo",test]