version: "3.8"

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CA_CERTIFICATE=${CA_CERTIFICATE}
        - SERVER_CERTIFICATE=${SERVER_CERTIFICATE}
        - SERVER_PRIVATE_KEY=${SERVER_PRIVATE_KEY}

    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5000:5671" # RabbitMQ SSL port
      - "4000:15672" # RabbitMQ management UI port
    command: ["cat",/etc/rabbitmq/ssl/ca_certifcate.pem]
    
    

  
