name: Docker Compose

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        env:
          CA_CERTIFICATE: "${{ secrets.CA_CERTIFICATE }}"
          SERVER_CERTIFICATE: "${{ secrets.SERVER_CERTIFICATE }}"
          SERVER_PRIVATE_KEY: "${{ secrets.SERVER_PRIVATE_KEY }}"
          
        run: |
          docker-compose up -d --build
          docker-compose logs rabbitmq
        working-directory: ./