name: Docker Build and Test

on:
  pull_request:
    branches:
      - main # Change this to your main branch name if different

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build --file Dockerfile --tag my-rabbitmq-image .

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start RabbitMQ Container
        run: |
          docker run -d \
            -p 5671:5671 \
            -p 15672:15672 \
            --name rabbitmq-container \
            my-rabbitmq-image

      # Add your test steps here to test the RabbitMQ instance running in the container

      - name: Stop RabbitMQ Container
        run: docker stop rabbitmq-container
