name: Docker Compose

on:
  push:
    branches:
      - main # adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Add new steps to set up SSL certificate
      - name: Set up SSL certificate
        run: |
          sudo mkdir -p /etc/rabbitmq/ssl
          echo "$CA_CERTIFICATE" > /etc/rabbitmq/ssl/ca_certificate.pem

      - name: Build and run Docker Compose
        env:
          CA_CERTIFICATE: ${{ secrets.CA_CERTIFICATE }}
        run: |
          docker-compose up -d --build
          docker-compose logs rabbitmq
        working-directory: ./
