name: Docker Compose

on:
  push:
    branches:
      - main # adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        env:
          test: ${{ secrets.CA_CERTIFICATE }}
        run: |
          export test="${test}"
          docker-compose up -d --build
          docker-compose logs rabbitmq
        working-directory: ./
